language: python
sudo: required
branches:
  only:
  - master
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y texlive-latex-recommended texlive-xetex texlive-luatex
  - sudo apt-get install -y pandoc
script:
  - ./build_notes.sh
